cminpack.cc File Reference
cminpack.cc File Reference
#include <cstring>
#include <cminpack.h>
#include "roboptim/core/function.hh"
#include "roboptim/core/problem.hh"
#include "roboptim/core/solver-error.hh"
#include "roboptim/core/plugin/cminpack.hh"
#include "roboptim/core/plugin/cminpack/config.hh"
Namespaces
roboptim
roboptim::cminpack
Typedefs
typedef
SolverWithJacobian::parent_t solver_t
Functions
int roboptim_plugin_cminpack_fcn (void *p, int ROBOPTIM_DEBUG_ONLY(m), int ROBOPTIM_DEBUG_ONLY(n), const double *x, double *fvec, double *fjrow, int iflag)
ROBOPTIM_CORE_PLUGIN_CMINPACK_DLLEXPORT
unsigned getSizeOfProblem ()
ROBOPTIM_CORE_PLUGIN_CMINPACK_DLLEXPORT
const char * getTypeIdOfConstraintsList ()
ROBOPTIM_CORE_PLUGIN_CMINPACK_DLLEXPORT
solver_t * create (const SolverWithJacobian::problem_t &pb)
ROBOPTIM_CORE_PLUGIN_CMINPACK_DLLEXPORT
void destroy (solver_t *p)
Typedef Documentation
typedef SolverWithJacobian::parent_t solver_t
Function Documentation
ROBOPTIM_CORE_PLUGIN_CMINPACK_DLLEXPORT solver_t * create (const SolverWithJacobian::problem_t & pb)
ROBOPTIM_CORE_PLUGIN_CMINPACK_DLLEXPORT void destroy (solver_t * p)
ROBOPTIM_CORE_PLUGIN_CMINPACK_DLLEXPORT unsigned getSizeOfProblem ()
ROBOPTIM_CORE_PLUGIN_CMINPACK_DLLEXPORT const char * getTypeIdOfConstraintsList ()
int roboptim_plugin_cminpack_fcn (void * p, int ROBOPTIM_DEBUG_ONLYm, int ROBOPTIM_DEBUG_ONLYn, const double * x, double * fvec, double * fjrow, int iflag)
References roboptim::cminpack::SolverWithJacobian::jacobianRow(), roboptim::cminpack::SolverWithJacobian::m(), roboptim::cminpack::SolverWithJacobian::n(), roboptim::cminpack::SolverWithJacobian::parameter(), and roboptim::cminpack::SolverWithJacobian::value().
Referenced by roboptim::cminpack::SolverWithJacobian::solve().