roboptim::cminpack::SolverWithJacobian Class Reference
roboptim::cminpack::SolverWithJacobian Class Reference
Solver implementing a variant of Levenberg-Marquardt algorithm.
#include <roboptim/core/plugin/cminpack.hh>
Public Types
typedef Solver< EigenMatrixDense > parent_t
Parent type.
typedef SumOfC1Squares function_t
Cost function type.
typedef function_t::argument_t argument_t
Type of result.
typedef function_t::argument_ref argument_ref
typedef
function_t::const_argument_ref const_argument_ref
typedef function_t::result_t result_t
Type of result.
typedef function_t::gradient_t gradient_t
Type of gradient.
typedef
function_t::const_gradient_ref const_gradient_ref
typedef function_t::size_type size_type
Size type.
Public Member Functions
SolverWithJacobian (const problem_t &problem)
Constructot by problem.
virtual ~SolverWithJacobian ()
virtual void solve ()
Solve the optimization problem.
size_type n () const
Number of variables.
size_type m () const
Number of functions.
argument_t & parameter ()
Get parameter.
const argument_t & parameter () const
const argument_t & value () const
Get value.
const gradient_t & jacobianRow (size_type iRow) const
Get Jacobian.
const boost::shared_ptr< const
DifferentiableFunction > baseCost () const
Detailed Description
Solver implementing a variant of Levenberg-Marquardt algorithm.
This solver tries to minimize the euclidean norm of a vector valued function.
Member Typedef Documentation
typedef function_t::argument_ref roboptim::cminpack::SolverWithJacobian::argument_ref
typedef function_t::argument_t roboptim::cminpack::SolverWithJacobian::argument_t
Type of result.
typedef function_t::const_argument_ref roboptim::cminpack::SolverWithJacobian::const_argument_ref
typedef function_t::const_gradient_ref roboptim::cminpack::SolverWithJacobian::const_gradient_ref
typedef SumOfC1Squares roboptim::cminpack::SolverWithJacobian::function_t
Cost function type.
typedef function_t::gradient_t roboptim::cminpack::SolverWithJacobian::gradient_t
Type of gradient.
typedef Solver<EigenMatrixDense> roboptim::cminpack::SolverWithJacobian::parent_t
Parent type.
typedef function_t::result_t roboptim::cminpack::SolverWithJacobian::result_t
Type of result.
typedef function_t::size_type roboptim::cminpack::SolverWithJacobian::size_type
Size type.
Constructor & Destructor Documentation
roboptim::cminpack::SolverWithJacobian::SolverWithJacobian (const problem_t & problem) explicit
Constructot by problem.
roboptim::cminpack::SolverWithJacobian::~SolverWithJacobian () virtual
Member Function Documentation
const boost::shared_ptr<const DifferentiableFunction> roboptim::cminpack::SolverWithJacobian::baseCost () const inline
const gradient_t& roboptim::cminpack::SolverWithJacobian::jacobianRow (size_type iRow) const inline
Get Jacobian.
Referenced by roboptim_plugin_cminpack_fcn().
size_type roboptim::cminpack::SolverWithJacobian::m () const inline
Number of functions.
Referenced by roboptim_plugin_cminpack_fcn().
size_type roboptim::cminpack::SolverWithJacobian::n () const inline
Number of variables.
Referenced by roboptim_plugin_cminpack_fcn().
argument_t& roboptim::cminpack::SolverWithJacobian::parameter () inline
Get parameter.
Referenced by roboptim_plugin_cminpack_fcn().
const argument_t& roboptim::cminpack::SolverWithJacobian::parameter () const inline
void roboptim::cminpack::SolverWithJacobian::solve () virtual
Solve the optimization problem.
References roboptim_plugin_cminpack_fcn().
const argument_t& roboptim::cminpack::SolverWithJacobian::value () const inline
Get value.
Referenced by roboptim_plugin_cminpack_fcn().